name: update-table

on:
  schedule:
    - cron: '28 6 */3 * *'

jobs:
  update-spreadsheet:
    runs-on: ubuntu-latest
    timeout-minutes: 7

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install Python 3.14.x
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '3.14'

      - name: Prepare the environment
        run: pip3 install -r requirements.txt

      - name: Download the latest AllCertificateRecordsCSVFormat (v4)
        run: curl --connect-timeout 30 --max-time 300 --location -O https://ccadb.my.salesforce-sites.com/ccadb/AllCertificateRecordsCSVFormatv4

      - name: Generate the spreadsheet
        run: python3 convert.py

      - name: Prepare materials for pages
        run: |
          mkdir build
          cp -p CCADB-certificates.xlsx build/

      - name: Upload materials for pages as an artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa  # v3.0.1
        with:
          path: build

      - name: Deploy to Google Spreadsheet
        run: |
          ls -l CCADB-certificates.xlsx
          curl --connect-timeout 5 --fail --max-time 60 --no-keepalive --output /dev/null --retry 0 --silent --show-error --request POST --header 'Content-Type: application/octet-stream' --data-binary @CCADB-certificates.xlsx "${{ secrets.GAS_WEBAPP_DEPLOY_URL }}"


  deploy-to-pages:
    needs: update-spreadsheet
    runs-on: ubuntu-latest
    timeout-minutes: 2

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}/CCADB-certificates.xlsx

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e  # v4.0.5
