name: CI

on:
  schedule:
    - cron: '28 6 */3 * *'

jobs:
  update-spreadsheet:
    runs-on: ubuntu-latest
    timeout-minutes: 7

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install Python 3.11.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Prepare the environment
        run: pip3 install openpyxl lxml countrycode==0.4.0

      - name: Download the latest AllCertificateRecordsCSVFormat
        run: curl --connect-timeout 30 --max-time 300 --location -O https://ccadb.my.salesforce-sites.com/ccadb/AllCertificateRecordsCSVFormat

      - name: Generate the spreadsheet
        run: python3 convert.py

      - name: Prepare materials for pages
        run: |
          mkdir build
          cp -p CCADB-certificates.xlsx build/

      - name: Upload materials for pages as an artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy to Google Spreadsheet
        run: |
          ls -l CCADB-certificates.xlsx
          curl --connect-timeout 5 --fail --max-time 60 --no-keepalive --output /dev/null --retry 0 --silent --show-error --request POST --header 'Content-Type: application/octet-stream' --data-binary @CCADB-certificates.xlsx "${{ secrets.GAS_WEBAPP_DEPLOY_URL }}"


  deploy-to-pages:
    needs: update-spreadsheet
    runs-on: ubuntu-latest
    timeout-minutes: 2
    
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
